### PR TITLE
Upgrade to support webpack 2

### PR DESCRIPTION
**Pull request by hieuunguyeen**

### CODE REVIEW

**Review by medikoo — APPROVED** [review]
I'm not that familiar with Webpack but if that works, then good :)

Why we invest time into it now? Is it to avoid unnecessary transpilation of ES2017 code (as webpack 1 stumbled on that) ?

**Comment by medikoo** [comment]
Also safe way, would be to
1. Version it, and publish it to our private npm repo
2. Propose PR to `maas-backend` where reference this dep via semver
2. Apply this change with major
3. Prepare MB PR with this dep major bumped

**Comment by hieuunguyeen** [comment]
> Why we invest time into it now? Is it to avoid unnecessary transpilation of ES2017 code (as webpack 1 stumbled on that) ?

To avoid transpiling async/await and ES2016 code. Basically i try to trim down as much as possible the needs of babel in our codebase

**Comment by hieuunguyeen** [comment]
@laardee what do you think about this being on our private repo?

**Pull request merged**
